//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleEntrada
    {
        public int id_detalle { get; set; }
        public int id_producto { get; set; }
        public int cantidad { get; set; }
        public Nullable<int> id_orden { get; set; }
    
        public virtual OrdenEntrada OrdenEntrada { get; set; }
        public virtual EPP EPP { get; set; }
    }
}
