//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EPP()
        {
            this.DetalleEntrada = new HashSet<DetalleEntrada>();
        }
    
        public int id_epp { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
        public int cantidad { get; set; }
        public string comentario { get; set; }
        public int id_categoria { get; set; }
        public int id_user { get; set; }
        public int estado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEntrada> DetalleEntrada { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
