//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCSC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestion_eppEntities1 : DbContext
    {
        public gestion_eppEntities1()
            : base("name=gestion_eppEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<DetalleEntrada> DetalleEntrada { get; set; }
        public virtual DbSet<DetalleSalida> DetalleSalida { get; set; }
        public virtual DbSet<OrdenEntrada> OrdenEntrada { get; set; }
        public virtual DbSet<OrdenSalida> OrdenSalida { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<EPP> EPP { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
