//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenSalida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenSalida()
        {
            this.DetalleSalida = new HashSet<DetalleSalida>();
        }
    
        public int id_orden { get; set; }
        public System.DateTime fecha_orden { get; set; }
        public Nullable<int> user_entrega { get; set; }
        public int user_pide { get; set; }
        public string ubicacion { get; set; }
        public int id_carrera { get; set; }
        public string periodo_uso { get; set; }
        public Nullable<int> cant_alumnos { get; set; }
        public System.DateTime fecha_requerida { get; set; }
        public Nullable<int> cant_docentes { get; set; }
        public string comentario { get; set; }
        public int id_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSalida> DetalleSalida { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Carrera Carrera { get; set; }
    }
}
